{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracearr.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracearr.redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "tracearr.redis.selectorLabels" . | nindent 4 }}
{{- end }}
